---
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - acceptance/**/*
    - vendor/**/*

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
    - 'lib/facter/resolvers/windows/ffi/networking_ffi.rb'
    - 'lib/facter/util/facts/windows_release_finder.rb'

Style/IfUnlessModifier:
  Enabled: false

# $stdout is preferred because it refers to the *current* stdout stream, while
# STDOUT refers to the original stream. However, we can't just switch to using
# $stdout, because it may have been assigned to a different object than STDOUT,
# such as a IO to a file.
Style/GlobalStdStream:
  Exclude:
    - 'lib/facter.rb'
    - 'lib/facter/framework/cli/cli_launcher.rb'
    - 'lib/facter/framework/logging/logger.rb'
    - 'spec/framework/core/fact/internal/internal_fact_manager_spec.rb'
    - 'spec/framework/logging/logger_spec.rb'
