---
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop_checks:
    runs-on: ubuntu-20.04
    name: RuboCop
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4

      - name: Rubocop checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install --jobs 3 --retry 3
      - run: bundle exec rubocop --parallel

